# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ba6b66a3cf97d0855bba7d6507c9a15964afd48a642c8e4003598acf785bba51280d1c55a042c7b1791c790a987ea0353e3ce25ad29a7f6f101aa2dc43801dcf

test:
  secret_key_base: e4eefc456709ee7aa7f4d00084087a26b369a4f5360a8a1cc96d4d7e37f6ba7bae81f13973b41732575ab329f2a2bc87519d87de3aa5ad51339f68dfd308849f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
